### ISSUE TITLE
can't use the source because the license isn't explicit

### ISSUE THREAD

**Issue by robertpateii** [evangipson/chessy#1]
I appreciate you putting this out there, but without a more explicit license this code can only be reused in projects where the developer has the luxury to not care about following the law. Which is fine if that's your goal, but it sounds like you want this to be under more of an BSD/Apache/MIT license.

If you're familiar with creative commons then I wrote this [comparison of software licenses to creative commons](http://www.robertpate.net/blog/2011/comparison-of-free-software-licenses-to-creative-commons/) back in 2011. It's got some good links, but I should also mention that GitHub has a really great easy [license picker](http://choosealicense.com/) too.

**Comment by evangipson** [comment]
Thanks for this info! It was a good read. I was familiar with creative commons but not MIT/BSD/Apache. I ended up using the license picker, but I read your blog too. Great stuff!

Ended up going with MIT for my code projects, and I've been thinking I should probably use Creative Commons for the developer protips, since it's not code.

**Comment by robertpateii** [comment]
Oh yeah good call on the cc for protip.
